# Asteroid Dataset

<h3>Data Source And Method of Collection</h3>

I have collected this Dataset from which is officially maintained by Jet Propulsion Laboratory of California Institute of Technology which is an organization under NASA. In this Dataset all kinds of Data related to Asteroid is included. This Dataset is publicly available in their website. The Basic Definitions of the Columns have been given below.
Website Link- JPL Small-Body Database Search Engine

<h3>Basic Column Definition</h3>

1. SPK-ID: Object primary SPK-ID
2. Object ID: Object internal database ID
3. Object fullname: Object full name/designation
4. pdes: Object primary designation
5. name: Object IAU name
6. NEO: Near-Earth Object (NEO) flag
7. PHA: Potentially Hazardous Asteroid (PHA) flag
8. H: Absolute magnitude parameter
9. Diameter: object diameter (from equivalent sphere) km Unit
10. Albedo: Geometric albedo
11. Diameter_sigma: 1-sigma uncertainty in object diameter km Unit
12. Orbit_id: Orbit solution ID
13. Epoch: Epoch of osculation in modified Julian day form
14. Equinox: Equinox of reference frame
15. e: Eccentricity
16. a: Semi-major axis au Unit
17. q: perihelion distance au Unit
18. i: inclination; angle with respect to x-y ecliptic plane
19. tp: Time of perihelion passage TDB Unit
20. moid_ld: Earth Minimum Orbit Intersection Distance au Unit

In [2]:
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

In [14]:
# reading the dataset
data = pd.read_csv("/Users/briankimanzi/Documents/Excel/Asteroid Dataset.csv")
data

,id,spkid,full_name,pdes,name,prefix,neo,pha,H,diameter,...,sigma_i,sigma_om,sigma_w,sigma_ma,sigma_ad,sigma_n,sigma_tp,sigma_per,class,rms
0,a0000001,2000001,1 Ceres,1,Ceres,NaN,N,N,3.400,939.400,...,4.608900e-09,6.168800e-08,6.624800e-08,7.820700e-09,1.111300e-11,1.196500e-12,3.782900e-08,9.415900e-09,MBA,0.43301
1,a0000002,2000002,2 Pallas,2,Pallas,NaN,N,N,4.200,545.000,...,3.469400e-06,6.272400e-06,9.128200e-06,8.859100e-06,4.961300e-09,4.653600e-10,4.078700e-05,3.680700e-06,MBA,0.35936
2,a0000003,2000003,3 Juno,3,Juno,NaN,N,N,5.330,246.596,...,3.223100e-06,1.664600e-05,1.772100e-05,8.110400e-06,4.363900e-09,4.413400e-10,3.528800e-05,3.107200e-06,MBA,0.33848
3,a0000004,2000004,4 Vesta,4,Vesta,NaN,N,N,3.000,525.400,...,2.170600e-07,3.880800e-07,1.789300e-07,1.206800e-06,1.648600e-09,2.612500e-10,4.103700e-06,1.274900e-06,MBA,0.39980
4,a0000005,2000005,5 Astraea,5,Astraea,NaN,N,N,6.900,106.699,...,2.740800e-06,2.894900e-05,2.984200e-05,8.303800e-06,4.729000e-09,5.522700e-10,3.474300e-05,3.490500e-06,MBA,0.52191
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
958519,bPLS6013,3246801,(6013 P-L),6013 P-L,NaN,NaN,N,N,17.135,NaN,...,6.969000e+00,7.433000e+00,4.631100e+01,2.738300e+01,1.041200e+00,1.652100e-01,1.309700e+02,7.264900e+02,MBA,0.23839
958520,bPLS6331,3246834,(6331 P-L),6331 P-L,NaN,NaN,N,N,18.500,NaN,...,1.563500e-05,5.598600e-05,2.380400e-04,1.298200e-04,2.418900e-08,3.346100e-09,4.690200e-04,1.578500e-05,MBA,0.53633
958521,bPLS6344,3013075,(6344 P-L),6344 P-L,NaN,NaN,Y,Y,20.400,NaN,...,1.853300e-05,5.691700e-05,8.969200e-05,5.272600e-05,1.650100e-07,1.101600e-08,2.830600e-04,9.127500e-05,APO,0.51556
958522,bT2S2060,3246457,(2060 T-2),2060 T-2,NaN,NaN,N,N,18.071,NaN,...,5.448800e-01,4.391600e+00,1.898800e+01,1.083800e+01,7.171600e-01,1.016700e-01,3.898400e+01,5.035500e+02,MBA,0.25641
958523,bT3S2678,3246553,(2678 T-3),2678 T-3,NaN,NaN,N,N,18.060,NaN,...,1.102300e+00,3.117000e-01,1.284300e+00,4.736100e-01,1.626700e-01,2.487900e-02,5.523600e+00,1.064800e+02,MBA,0.26980

In [11]:
# Exploring the data
def explore(x):
    print("Asteroid data type")
    print("======================================")
    print(data.dtypes)
    print()
    print("Asteroid data columns")
    print("======================================")
    print(data.columns)
    print()
    print("Asteroid data insight")
    print("======================================")
    print(data.describe())

In [13]:
print(explore(data))

Asteroid data type
======================================
id                 object
spkid               int64
full_name          object
pdes               object
name               object
prefix             object
neo                object
pha                object
H                 float64
diameter          float64
albedo            float64
diameter_sigma    float64
orbit_id           object
epoch             float64
epoch_mjd           int64
epoch_cal         float64
equinox            object
e                 float64
a                 float64
q                 float64
i                 float64
om                float64
w                 float64
ma                float64
ad                float64
n                 float64
tp                float64
tp_cal            float64
per               float64
per_y             float64
moid              float64
moid_ld           float64
sigma_e           float64
sigma_a           float64
sigma_q           float64
sigma_i           float64
sigma_om          float64
sigma_w           float64
sigma_ma          float64
sigma_ad          float64
sigma_n           float64
sigma_tp          float64
sigma_per         float64
class              object
rms               float64
dtype: object

Asteroid data columns
======================================
Index(['id', 'spkid', 'full_name', 'pdes', 'name', 'prefix', 'neo', 'pha', 'H',
       'diameter', 'albedo', 'diameter_sigma', 'orbit_id', 'epoch',
       'epoch_mjd', 'epoch_cal', 'equinox', 'e', 'a', 'q', 'i', 'om', 'w',
       'ma', 'ad', 'n', 'tp', 'tp_cal', 'per', 'per_y', 'moid', 'moid_ld',
       'sigma_e', 'sigma_a', 'sigma_q', 'sigma_i', 'sigma_om', 'sigma_w',
       'sigma_ma', 'sigma_ad', 'sigma_n', 'sigma_tp', 'sigma_per', 'class',
       'rms'],
      dtype='object')

Asteroid data insight
======================================
              spkid              H       diameter         albedo  \
count  9.585240e+05  952261.000000  136209.000000  135103.000000
mean   3.810114e+06      16.906411       5.506429       0.130627
std    6.831541e+06       1.790405       9.425164       0.110323
min    2.000001e+06      -1.100000       0.002500       0.001000
25%    2.239632e+06      16.100000       2.780000       0.053000
50%    2.479262e+06      16.900000       3.972000       0.079000
75%    3.752518e+06      17.714000       5.765000       0.190000
max    5.401723e+07      33.200000     939.400000       1.000000

       diameter_sigma         epoch      epoch_mjd     epoch_cal  \
count   136081.000000  9.585240e+05  958524.000000  9.585240e+05
mean         0.479184  2.458869e+06   58868.781950  2.019693e+07
std          0.782895  7.016716e+02     701.671573  1.930354e+04
min          0.000500  2.425052e+06   25051.000000  1.927062e+07
25%          0.180000  2.459000e+06   59000.000000  2.020053e+07
50%          0.332000  2.459000e+06   59000.000000  2.020053e+07
75%          0.620000  2.459000e+06   59000.000000  2.020053e+07
max        140.000000  2.459000e+06   59000.000000  2.020053e+07

                   e              a  ...       sigma_q       sigma_i  \
count  958524.000000  958524.000000  ...  9.386020e+05  9.386020e+05
mean        0.156116       2.902143  ...  1.982929e+01  1.168449e+00
std         0.092643      39.719503  ...  2.903785e+03  1.282231e+02
min         0.000000  -14702.447872  ...  1.956900e-11  4.608900e-09
25%         0.092193       2.387835  ...  1.462000e-07  6.095900e-06
50%         0.145002       2.646969  ...  2.271900e-07  8.688800e-06
75%         0.200650       3.001932  ...  6.583200e-07  1.591500e-05
max         1.855356   33488.895955  ...  1.015000e+06  5.533000e+04

           sigma_om       sigma_w      sigma_ma      sigma_ad       sigma_n  \
count  9.386020e+05  9.386020e+05  9.386020e+05  9.385980e+05  9.386020e+05
mean   5.310234e+00  1.370062e+06  1.369977e+06  2.131453e+01  5.060221e-02
std    1.333381e+03  9.158996e+08  9.158991e+08  7.197034e+03  9.814953e+00
min    6.168800e-08  6.624800e-08  7.820700e-09  1.111300e-11  1.196500e-12
25%    3.619400e-05  5.755000e-05  2.573700e-05  2.340900e-08  2.768800e-09
50%    6.642550e-05  1.047100e-04  4.900100e-05  4.359000e-08  4.638000e-09
75%    1.609775e-04  3.114400e-04  1.718900e-04  1.196600e-07  1.124000e-08
max    1.199100e+06  8.845100e+11  8.845100e+11  5.509700e+06  7.698800e+03

           sigma_tp     sigma_per            rms
count  9.386020e+05  9.385980e+05  958522.000000
mean   4.312780e+08  8.525815e+04       0.561153
std    2.953046e+11  2.767681e+07       2.745700
min    3.782900e-08  9.415900e-09       0.000000
25%    1.110900e-04  1.794500e-05       0.518040
50%    2.230800e-04  3.501700e-05       0.566280
75%    8.139600e-04  9.775475e-05       0.613927
max    2.853100e+14  1.910700e+10    2686.600000

[8 rows x 35 columns]
None

In [17]:
# code to display all the columns
pd.set_option('display.max_columns', None)
data

,id,spkid,full_name,pdes,name,prefix,neo,pha,H,diameter,albedo,diameter_sigma,orbit_id,epoch,epoch_mjd,epoch_cal,equinox,e,a,q,i,om,w,ma,ad,n,tp,tp_cal,per,per_y,moid,moid_ld,sigma_e,sigma_a,sigma_q,sigma_i,sigma_om,sigma_w,sigma_ma,sigma_ad,sigma_n,sigma_tp,sigma_per,class,rms
0,a0000001,2000001,1 Ceres,1,Ceres,NaN,N,N,3.400,939.400,0.0900,0.200,JPL 47,2458600.5,58600,20190427.0,J2000,0.076009,2.769165,2.558684,10.594067,80.305531,73.597695,77.372098,2.979647,0.213885,2.458239e+06,2.018043e+07,1683.145703,4.608202,1.594780,620.640533,4.819000e-12,1.032800e-11,1.956900e-11,4.608900e-09,6.168800e-08,6.624800e-08,7.820700e-09,1.111300e-11,1.196500e-12,3.782900e-08,9.415900e-09,MBA,0.43301
1,a0000002,2000002,2 Pallas,2,Pallas,NaN,N,N,4.200,545.000,0.1010,18.000,JPL 37,2459000.5,59000,20200531.0,J2000,0.229972,2.773841,2.135935,34.832932,173.024741,310.202392,144.975675,3.411748,0.213345,2.458321e+06,2.018072e+07,1687.410992,4.619880,1.234290,480.348639,3.193400e-08,4.033700e-09,8.832200e-08,3.469400e-06,6.272400e-06,9.128200e-06,8.859100e-06,4.961300e-09,4.653600e-10,4.078700e-05,3.680700e-06,MBA,0.35936
2,a0000003,2000003,3 Juno,3,Juno,NaN,N,N,5.330,246.596,0.2140,10.594,JPL 112,2459000.5,59000,20200531.0,J2000,0.256936,2.668285,1.982706,12.991043,169.851482,248.066193,125.435355,3.353865,0.226129,2.458446e+06,2.018112e+07,1592.013769,4.358696,1.034290,402.514639,3.052000e-08,3.471800e-09,8.139200e-08,3.223100e-06,1.664600e-05,1.772100e-05,8.110400e-06,4.363900e-09,4.413400e-10,3.528800e-05,3.107200e-06,MBA,0.33848
3,a0000004,2000004,4 Vesta,4,Vesta,NaN,N,N,3.000,525.400,0.4228,0.200,JPL 35,2458600.5,58600,20190427.0,J2000,0.088721,2.361418,2.151909,7.141771,103.810804,150.728541,95.861938,2.570926,0.271609,2.458248e+06,2.018051e+07,1325.432763,3.628837,1.139480,443.451432,2.332100e-10,1.514300e-09,1.928600e-09,2.170600e-07,3.880800e-07,1.789300e-07,1.206800e-06,1.648600e-09,2.612500e-10,4.103700e-06,1.274900e-06,MBA,0.39980
4,a0000005,2000005,5 Astraea,5,Astraea,NaN,N,N,6.900,106.699,0.2740,3.140,JPL 114,2459000.5,59000,20200531.0,J2000,0.190913,2.574037,2.082619,5.367427,141.571026,358.648418,17.846343,3.065455,0.238661,2.458926e+06,2.020032e+07,1508.414421,4.129814,1.095750,426.433027,2.373700e-08,3.970900e-09,6.092400e-08,2.740800e-06,2.894900e-05,2.984200e-05,8.303800e-06,4.729000e-09,5.522700e-10,3.474300e-05,3.490500e-06,MBA,0.52191
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
958519,bPLS6013,3246801,(6013 P-L),6013 P-L,NaN,NaN,N,N,17.135,NaN,NaN,NaN,JPL 5,2437203.5,37203,19600926.0,J2000,0.185919,2.280861,1.856807,5.984416,194.229902,195.442802,342.057565,2.704916,0.286125,2.437266e+06,1.960113e+07,1258.191614,3.444741,0.861979,335.456367,2.142200e-02,8.779900e-01,7.299800e-01,6.969000e+00,7.433000e+00,4.631100e+01,2.738300e+01,1.041200e+00,1.652100e-01,1.309700e+02,7.264900e+02,MBA,0.23839
958520,bPLS6331,3246834,(6331 P-L),6331 P-L,NaN,NaN,N,N,18.500,NaN,NaN,NaN,8,2459000.5,59000,20200531.0,J2000,0.282920,2.334910,1.674319,8.082280,355.248239,5.216223,260.113042,2.995502,0.276248,2.459362e+06,2.021053e+07,1303.177916,3.567907,0.671242,261.227249,2.642000e-07,1.885500e-08,6.256300e-07,1.563500e-05,5.598600e-05,2.380400e-04,1.298200e-04,2.418900e-08,3.346100e-09,4.690200e-04,1.578500e-05,MBA,0.53633
958521,bPLS6344,3013075,(6344 P-L),6344 P-L,NaN,NaN,Y,Y,20.400,NaN,NaN,NaN,17,2459000.5,59000,20200531.0,J2000,0.662446,2.817152,0.950941,4.679278,182.982832,234.894852,240.473601,4.683363,0.208444,2.459574e+06,2.021123e+07,1727.085364,4.728502,0.035589,13.850093,6.636800e-08,9.925600e-08,1.687100e-07,1.853300e-05,5.691700e-05,8.969200e-05,5.272600e-05,1.650100e-07,1.101600e-08,2.830600e-04,9.127500e-05,APO,0.51556
958522,bT2S2060,3246457,(2060 T-2),2060 T-2,NaN,NaN,N,N,18.071,NaN,NaN,NaN,JPL 3,2441956.5,41956,19731001.0,J2000,0.202053,2.373137,1.893638,0.732484,176.499082,198.026527,355.351127,2.852636,0.269600,2.441974e+06,1.973102e+07,1335.311579,3.655884,0.893896,347.877506,3.169800e-02,5.966200e-01,5.478400e-01,5.448800e-01,4.391600e+00,1.898800e+01,1.083800e+01,7.171600e-01,1.016700e-01,3.898400e+01,5.035500e+02,MBA,0.25641
958523,bT3S2678,3246553,(2678 T-3),2678 T-3,NaN,NaN,N,N,18.060,NaN,NaN,NaN,JPL 3,2443429.5,43429,19771013.0,J2000,0.258348,2.260404,1.676433,9.661947,204.512448,148.496988,15.320134,2.844376,0.290018,2.443377e+06,1.977082e+07,1241.302609,3.398501,0.680220,264.721217,1.486800e-02,1.292700e-01,6.252600e-02,1.102300e+00,3.117000e-01,1.284300e+00,4.736100e-01,1.626700e-01,2.487900e-02,5.523600e+00,1.064800e+02,MBA,0.26980

In [19]:
# changing the number format of the columns from scientific to float
pd.set_option('display.float_format', lambda x: '%.2f' % x)
data

,id,spkid,full_name,pdes,name,prefix,neo,pha,H,diameter,albedo,diameter_sigma,orbit_id,epoch,epoch_mjd,epoch_cal,equinox,e,a,q,i,om,w,ma,ad,n,tp,tp_cal,per,per_y,moid,moid_ld,sigma_e,sigma_a,sigma_q,sigma_i,sigma_om,sigma_w,sigma_ma,sigma_ad,sigma_n,sigma_tp,sigma_per,class,rms
0,a0000001,2000001,1 Ceres,1,Ceres,NaN,N,N,3.40,939.40,0.09,0.20,JPL 47,2458600.50,58600,20190427.00,J2000,0.08,2.77,2.56,10.59,80.31,73.60,77.37,2.98,0.21,2458238.75,20180430.25,1683.15,4.61,1.59,620.64,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,MBA,0.43
1,a0000002,2000002,2 Pallas,2,Pallas,NaN,N,N,4.20,545.00,0.10,18.00,JPL 37,2459000.50,59000,20200531.00,J2000,0.23,2.77,2.14,34.83,173.02,310.20,144.98,3.41,0.21,2458320.96,20180721.46,1687.41,4.62,1.23,480.35,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,MBA,0.36
2,a0000003,2000003,3 Juno,3,Juno,NaN,N,N,5.33,246.60,0.21,10.59,JPL 112,2459000.50,59000,20200531.00,J2000,0.26,2.67,1.98,12.99,169.85,248.07,125.44,3.35,0.23,2458445.79,20181123.29,1592.01,4.36,1.03,402.51,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,MBA,0.34
3,a0000004,2000004,4 Vesta,4,Vesta,NaN,N,N,3.00,525.40,0.42,0.20,JPL 35,2458600.50,58600,20190427.00,J2000,0.09,2.36,2.15,7.14,103.81,150.73,95.86,2.57,0.27,2458247.56,20180509.06,1325.43,3.63,1.14,443.45,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,MBA,0.40
4,a0000005,2000005,5 Astraea,5,Astraea,NaN,N,N,6.90,106.70,0.27,3.14,JPL 114,2459000.50,59000,20200531.00,J2000,0.19,2.57,2.08,5.37,141.57,358.65,17.85,3.07,0.24,2458925.72,20200317.22,1508.41,4.13,1.10,426.43,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,MBA,0.52
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
958519,bPLS6013,3246801,(6013 P-L),6013 P-L,NaN,NaN,N,N,17.14,NaN,NaN,NaN,JPL 5,2437203.50,37203,19600926.00,J2000,0.19,2.28,1.86,5.98,194.23,195.44,342.06,2.70,0.29,2437266.21,19601127.71,1258.19,3.44,0.86,335.46,0.02,0.88,0.73,6.97,7.43,46.31,27.38,1.04,0.17,130.97,726.49,MBA,0.24
958520,bPLS6331,3246834,(6331 P-L),6331 P-L,NaN,NaN,N,N,18.50,NaN,NaN,NaN,8,2459000.50,59000,20200531.00,J2000,0.28,2.33,1.67,8.08,355.25,5.22,260.11,3.00,0.28,2459362.08,20210527.58,1303.18,3.57,0.67,261.23,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,MBA,0.54
958521,bPLS6344,3013075,(6344 P-L),6344 P-L,NaN,NaN,Y,Y,20.40,NaN,NaN,NaN,17,2459000.50,59000,20200531.00,J2000,0.66,2.82,0.95,4.68,182.98,234.89,240.47,4.68,0.21,2459573.92,20211225.42,1727.09,4.73,0.04,13.85,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,APO,0.52
958522,bT2S2060,3246457,(2060 T-2),2060 T-2,NaN,NaN,N,N,18.07,NaN,NaN,NaN,JPL 3,2441956.50,41956,19731001.00,J2000,0.20,2.37,1.89,0.73,176.50,198.03,355.35,2.85,0.27,2441973.74,19731018.24,1335.31,3.66,0.89,347.88,0.03,0.60,0.55,0.54,4.39,18.99,10.84,0.72,0.10,38.98,503.55,MBA,0.26
958523,bT3S2678,3246553,(2678 T-3),2678 T-3,NaN,NaN,N,N,18.06,NaN,NaN,NaN,JPL 3,2443429.50,43429,19771013.00,J2000,0.26,2.26,1.68,9.66,204.51,148.50,15.32,2.84,0.29,2443376.68,19770821.18,1241.30,3.40,0.68,264.72,0.01,0.13,0.06,1.10,0.31,1.28,0.47,0.16,0.02,5.52,106.48,MBA,0.27

In [20]:
data

,id,spkid,full_name,pdes,name,prefix,neo,pha,H,diameter,albedo,diameter_sigma,orbit_id,epoch,epoch_mjd,epoch_cal,equinox,e,a,q,i,om,w,ma,ad,n,tp,tp_cal,per,per_y,moid,moid_ld,sigma_e,sigma_a,sigma_q,sigma_i,sigma_om,sigma_w,sigma_ma,sigma_ad,sigma_n,sigma_tp,sigma_per,class,rms
0,a0000001,2000001,1 Ceres,1,Ceres,NaN,N,N,3.40,939.40,0.09,0.20,JPL 47,2458600.50,58600,20190427.00,J2000,0.08,2.77,2.56,10.59,80.31,73.60,77.37,2.98,0.21,2458238.75,20180430.25,1683.15,4.61,1.59,620.64,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,MBA,0.43
1,a0000002,2000002,2 Pallas,2,Pallas,NaN,N,N,4.20,545.00,0.10,18.00,JPL 37,2459000.50,59000,20200531.00,J2000,0.23,2.77,2.14,34.83,173.02,310.20,144.98,3.41,0.21,2458320.96,20180721.46,1687.41,4.62,1.23,480.35,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,MBA,0.36
2,a0000003,2000003,3 Juno,3,Juno,NaN,N,N,5.33,246.60,0.21,10.59,JPL 112,2459000.50,59000,20200531.00,J2000,0.26,2.67,1.98,12.99,169.85,248.07,125.44,3.35,0.23,2458445.79,20181123.29,1592.01,4.36,1.03,402.51,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,MBA,0.34
3,a0000004,2000004,4 Vesta,4,Vesta,NaN,N,N,3.00,525.40,0.42,0.20,JPL 35,2458600.50,58600,20190427.00,J2000,0.09,2.36,2.15,7.14,103.81,150.73,95.86,2.57,0.27,2458247.56,20180509.06,1325.43,3.63,1.14,443.45,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,MBA,0.40
4,a0000005,2000005,5 Astraea,5,Astraea,NaN,N,N,6.90,106.70,0.27,3.14,JPL 114,2459000.50,59000,20200531.00,J2000,0.19,2.57,2.08,5.37,141.57,358.65,17.85,3.07,0.24,2458925.72,20200317.22,1508.41,4.13,1.10,426.43,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,MBA,0.52
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
958519,bPLS6013,3246801,(6013 P-L),6013 P-L,NaN,NaN,N,N,17.14,NaN,NaN,NaN,JPL 5,2437203.50,37203,19600926.00,J2000,0.19,2.28,1.86,5.98,194.23,195.44,342.06,2.70,0.29,2437266.21,19601127.71,1258.19,3.44,0.86,335.46,0.02,0.88,0.73,6.97,7.43,46.31,27.38,1.04,0.17,130.97,726.49,MBA,0.24
958520,bPLS6331,3246834,(6331 P-L),6331 P-L,NaN,NaN,N,N,18.50,NaN,NaN,NaN,8,2459000.50,59000,20200531.00,J2000,0.28,2.33,1.67,8.08,355.25,5.22,260.11,3.00,0.28,2459362.08,20210527.58,1303.18,3.57,0.67,261.23,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,MBA,0.54
958521,bPLS6344,3013075,(6344 P-L),6344 P-L,NaN,NaN,Y,Y,20.40,NaN,NaN,NaN,17,2459000.50,59000,20200531.00,J2000,0.66,2.82,0.95,4.68,182.98,234.89,240.47,4.68,0.21,2459573.92,20211225.42,1727.09,4.73,0.04,13.85,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,APO,0.52
958522,bT2S2060,3246457,(2060 T-2),2060 T-2,NaN,NaN,N,N,18.07,NaN,NaN,NaN,JPL 3,2441956.50,41956,19731001.00,J2000,0.20,2.37,1.89,0.73,176.50,198.03,355.35,2.85,0.27,2441973.74,19731018.24,1335.31,3.66,0.89,347.88,0.03,0.60,0.55,0.54,4.39,18.99,10.84,0.72,0.10,38.98,503.55,MBA,0.26
958523,bT3S2678,3246553,(2678 T-3),2678 T-3,NaN,NaN,N,N,18.06,NaN,NaN,NaN,JPL 3,2443429.50,43429,19771013.00,J2000,0.26,2.26,1.68,9.66,204.51,148.50,15.32,2.84,0.29,2443376.68,19770821.18,1241.30,3.40,0.68,264.72,0.01,0.13,0.06,1.10,0.31,1.28,0.47,0.16,0.02,5.52,106.48,MBA,0.27